### ISSUE TITLE
curios-forge-5.4.2+1.20.1 无法进入游戏

### ISSUE THREAD

**Issue by SeanChengN** [SolarMoonQAQ/Spyglass-of-Curios#1]
如题
[2023-11-10-3.log](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/13320575/2023-11-10-3.log)

**Comment by SolarMoonQAQ** [comment]
你好，尝试更新forge版本到47.2.0及以上试试！

**Comment by SolarMoonQAQ** [comment]
> 如题 [2023-11-10-3.log](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/13320575/2023-11-10-3.log)
你好，尝试更新forge版本到47.2.0及以上试试！

**Comment by SolarMoonQAQ** [comment]
> 如题 [2023-11-10-3.log](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/13320575/2023-11-10-3.log)

你好，尝试更新forge版本到47.2.0及以上试试！

**Comment by SeanChengN** [comment]
> > 如题 [2023-11-10-3.log](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/13320575/2023-11-10-3.log)
> 
> 你好，尝试更新forge版本到47.2.0及以上试试！

可以了，但是信雅互联用47.1.3，先搁置

**Comment by SolarMoonQAQ** [comment]
> > > 如题 [2023-11-10-3.log](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/13320575/2023-11-10-3.log)
> > 
> > 你好，尝试更新forge版本到47.2.0及以上试试！
> 
> 可以了，但是信雅互联用47.1.3，先搁置

现在快照版已支持47.1.3！😉
