### ISSUE TITLE
[Bug] 1.19.2 和光影产生的渲染Bug

### ISSUE THREAD

**Issue by QianFuv** [SolarMoonQAQ/Spyglass-of-Curios#10]
简单来说是装在饰品栏按C后某一角度某一缩放程度下会在十字线中心附近产生一个望远镜的虚影 稍后我会做复现和截图

**Comment by SolarMoonQAQ** [comment]
感谢反馈，已经修复！
如果急需的话可以发你一个修复版，不急的话年底会和新版本一起发布~

**Comment by QianFuv** [comment]
修复了啊已经 我还说一会做复现呢 不急 你按自己节奏来发版本就行

**Comment by SolarMoonQAQ** [comment]
已发布！

**Comment by QianFuv** [comment]
收到 感谢您在minecraft模组开发中的付出！
