### ISSUE TITLE
[1.20.1] Spyglass shown on-screen when zooming.

### ISSUE THREAD

**Issue by Sandriell** [SolarMoonQAQ/Spyglass-of-Curios#11]
When zooming in the spyglass is being rendered on the screen.

![2023-12-21_10 51 07](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/assets/10704907/e1eaf16b-516c-4076-a591-8078ac2d10b6)

Mod list: https://gist.github.com/Sandriell/dbcb507cc8b3a9f22fdf5ab82a773765
Forge: 47.2.17
Mod: spyglassofcurios-forge-1.20.1-1.5.1

**Comment by SolarMoonQAQ** [comment]
Same as #10,.Thank you for your feedback. Actually, it has been fixed, but due to my recent busy schedule, I haven't had the chance to release the fixed version yet. Whatever, It will be released within five days!

**Comment by SolarMoonQAQ** [comment]
Now fixed!
