### ISSUE TITLE
BUG - 饰品栏没装备望远镜按C第三人称也会抬手

### ISSUE THREAD

**Issue by QianFuv** [SolarMoonQAQ/Spyglass-of-Curios#12]
1.19.2 forge 如题

**Comment by SolarMoonQAQ** [comment]
额，其实不是bug，我想着设计成这样的，可以给玩家多个动作来着，需要的话以后可以加个配置自由开关~

**Comment by QianFuv** [comment]
啊这？感觉这个动作有点多余（确信
如果你不舍得就加个开关吧 关键是有点突兀qwq
有一种滑稽的喜感
