### ISSUE TITLE
[BUG]创建世界第一次使用望远镜时镜头的奇怪抖动

### ISSUE THREAD

**Issue by QianFuv** [SolarMoonQAQ/Spyglass-of-Curios#13]
https://youtu.be/ep3NqCStgw0?si=6VMtRU1TepGWt0LX

**Comment by SolarMoonQAQ** [comment]
请问有没有别的细节，比如您是用右键使用的还是按键？这个问题只发生在第一次使用吗？您的游戏版本我记得是1.19.2是吗？......
我在只装载mod的情况下试了下似乎没能复现，可能是别的原因？

**Comment by QianFuv** [comment]
在某一次更新之后就这样了 只发生在第一次使用 1.19.2forge 望远镜拿手里直接右键

**Comment by SolarMoonQAQ** [comment]
已修复！顺便把你上次的那个动作问题加到配置里去了~

**Comment by QianFuv** [comment]
感谢
