### ISSUE TITLE
与CMDCam同时安装会导致缩放失效

### ISSUE THREAD

**Issue by QianFuv** [SolarMoonQAQ/Spyglass-of-Curios#14]
https://www.curseforge.com/minecraft/mc-mods/cmdcam
https://github.com/CreativeMD/CMDCam

1.19.2 forge

**Comment by SolarMoonQAQ** [comment]
我仔细看了一下，那个模组在fov事件中直接把除了符合他模组条件的所有可能都return了，由于我用的mixin，和forge事件的fov计算逻辑不同，如果我要解决的话需要重写fov算法，因此短期内可能无法解决，非常抱歉。

**Comment by SolarMoonQAQ** [comment]
不过严格来说应该是那个模组的疏忽，因为他的写法会导致原版的望远镜也无法放大233

可惜的是作者已经表示不再支持1.19的更新
https://github.com/CreativeMD/CMDCam/issues/88

**Comment by QianFuv** [comment]
啊 懂了
