### ISSUE TITLE
Using Zoom Key without Spyglass on Multiplayer Server causes all players to lift their arms

### ISSUE THREAD

**Issue by IdrisQe** [SolarMoonQAQ/Spyglass-of-Curios#15]
Using the Zoom key while you don't have a spyglass causes you to lift your arm as if you were holding the spyglass up.

In singleplayer this works as expected, but on a server, this causes all players to raise their arms on your screen as if they had also pressed the hotkey (they cannot see themselves doing it so this is a clientside issue)

Version is 1.6.1 for Minecraft 1.20.1, using Forge 47.2.0

**Comment by SolarMoonQAQ** [comment]
Testing multiplayer games has always been a difficult part for me, so thank you for your feedback! If all goes well, this issue should have been fixed in version 1.7.0!
