### ISSUE TITLE
Problems with the default key (C) Somehow changing my mouse sensitivity and spyglass itself keeps moving while zoomed in

### ISSUE THREAD

**Issue by Sekwan2000** [SolarMoonQAQ/Spyglass-of-Curios#16]
I have no clue why this is happening, managed to fix the mouse sensitivity issue by changing the key bind to X but the spyglass zoom is still moving on it's own while zoomed in.

**Comment by SolarMoonQAQ** [comment]
I’m sorry, I don’t seem to understand what you mean by “still moving”. Are you referring to smooth movement like a cinematic camera? Or are you saying that the spyglass is moving on its own uncontrollably? If it’s the former, then it’s a new feature in version 1.6.3. If not, then it could be a bug.
Regarding the change in sensitivity, this is actually a new feature designed to prevent the spyglass from moving too quickly when the magnification is too high. However, it should only occur when using the spyglass. If it happens in other situations, then it is indeed a bug. If not, you can try to turn off this feature in the display settings in the configuration to see if the problem you mentioned still occurs, and if you find this feature inconvenient in any way, feel free to share your feedback.
Sorry for the inconvenience caused to you, I will do my best to meet your needs.

**Comment by SolarMoonQAQ** [comment]
Given that I suspect your issue may be related to the new features, your problem should be somewhat resolved in version 1.7.0. Therefore, I will close this issue for now. If you encounter any problems, feel free to reopen this issue or submit a new one at any time~
