### ISSUE TITLE
[1.20.1] Ticking Crash?

### ISSUE THREAD

**Issue by Gantros** [SolarMoonQAQ/Spyglass-of-Curios#17]
Was just playing around when the game crashed, the log is as follows:

[crash-2024-01-25_12.51.19-server.txt](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/14057672/crash-2024-01-25_12.51.19-server.txt)

**Comment by zeid0ne** [comment]
same error in single player

**Comment by IdrisQe** [comment]
Just updated to the new version, now I'm having this problem too.

**Comment by SolarMoonQAQ** [comment]
My apologies, due to my oversight, I failed to filter out the situation where non-players use items. Please try version 1.7.1, I would be happy to help if you have any further problems or suggestions!
