### ISSUE TITLE
放置盔甲架崩溃

### ISSUE THREAD

**Issue by QianFuv** [SolarMoonQAQ/Spyglass-of-Curios#18]
https://mclo.gs/EzjSUik
https://mclo.gs/4bSlcyx

**Comment by SolarMoonQAQ** [comment]
[spyglass_of_curios-forge-1.19.2-1.7.2.zip](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/14071813/spyglass_of_curios-forge-1.19.2-1.7.2.zip)
试试这个，昨天改代码竟然有一行没改全，泪目

**Comment by QianFuv** [comment]
我逝世 稍等:)

**Comment by QianFuv** [comment]
没问题了awa
