### ISSUE TITLE
[1.20.1] Roll back Forge Version to 47.1.3 from 47.2

### ISSUE THREAD

**Issue by ffuentesm** [SolarMoonQAQ/Spyglass-of-Curios#2]
The minecraft mod community for 1.20.1 stopped on the 47.1.3 forge version, meaning that there are MANY mods that do not work on any "new" forge version beyond that—making this mod 47.2 dependable exclude this mod from many mod lists as it will not work with manor mods, like ars and Create. 
And now on 1.20.2, the modding community will opt for NeoForge over Forge.

**Comment by SolarMoonQAQ** [comment]
> The minecraft mod community for 1.20.1 stopped on the 47.1.3 forge version, meaning that there are MANY mods that do not work on any "new" forge version beyond that—making this mod 47.2 dependable exclude this mod from many mod lists as it will not work with manor mods, like ars and Create. And now on 1.20.2, the modding community will opt for NeoForge over Forge.

Hey! thanks for your suggestion, but I think you misunderstood a bit. Personally, I am very willing to port mod to neoforge, but I am waiting for neoforge 1.20.2 to arrive. I don't know if you have noticed it, but in fact, I have already created a separate version for forge 47.1.3, It's just marked as an alpha version. You can try using it!

**Comment by SolarMoonQAQ** [comment]
> The minecraft mod community for 1.20.1 stopped on the 47.1.3 forge version, meaning that there are MANY mods that do not work on any "new" forge version beyond that—making this mod 47.2 dependable exclude this mod from many mod lists as it will not work with manor mods, like ars and Create.1.20.1 的 minecraft mod 社区在 47.1.3 forge 版本上停止了，这意味着除了这个版本之外，还有许多 mod 无法在任何“新”forge 版本上运行——使这个 mod 47.2 可靠地将这个 mod 从许多 mod 列表中排除，因为它不适用于庄园 mod，比如 ars 和 Create。 And now on 1.20.2, the modding community will opt for NeoForge over Forge.现在在 1.20.2 上，Mod 社区将选择 NeoForge 而不是 Forge。

Now the main version has already support forge 47.1.3~enjoy!
