### ISSUE TITLE
Is there a config somewhere?

### ISSUE THREAD

**Issue by xhatz** [SolarMoonQAQ/Spyglass-of-Curios#5]
Hello! I just discovered your mod and it's perfect for my project, but I was wondering, is there a config file somewhere? I would prefer to disable the other rendering modes of the spyglass as they don't really fit with the mood of the server, is it possible somewhere please? Tysm!

**Comment by SolarMoonQAQ** [comment]
> 你好！我刚刚发现了你的模组，它非常适合我的项目，但我想知道，某处有配置文件吗？我宁愿禁用望远镜的其他渲染模式，因为它们并不真正适合服务器的情绪，请问在某个地方可能吗？泰斯姆！

I’m very sorry, but there isn’t a configuration file to turn it off at the moment. However, since you’ve brought it up, I will add a configuration file in the next version to provide optional rendering configurations. Please be patient, and I will let you know when it’s done!

**Comment by SolarMoonQAQ** [comment]
> Hello! I just discovered your mod and it's perfect for my project, but I was wondering, is there a config file somewhere? I would prefer to disable the other rendering modes of the spyglass as they don't really fit with the mood of the server, is it possible somewhere please? Tysm!

Now there is a configuration file that allows you to choose to turn off! If there are any problems, feel free to let me know~
