### ISSUE TITLE
[1.20.1 Forge] New update causes spyglass duplication / off hand replacement.

### ISSUE THREAD

**Issue by PlayfulPiano** [SolarMoonQAQ/Spyglass-of-Curios#9]
If you hold down shift and then press your spyglass keybind, it'll replace your offhand item entirely and duplicate itself.

This is using v1.4.2 of the mod.

**Comment by SolarMoonQAQ** [comment]
To fix this issue I have almost restructured the mod logic, there should theoretically be no duplication bugs now, if there're any other issues, welcome to report to me!

**Comment by PlayfulPiano** [comment]
It seems to work great now, thank you!
